'use client';

import { useState } from 'react';
import { fmt } from '@/lib/finance';

const EXAMPLES = [
  'Why is Admin COGS Payroll and Benefits over budget?',
  'What are the largest expense items hitting SG&A other costs on InnerJoin?',
  'Which accounts are driving the RIA revenue shortfall?',
];

// Every table shown here came straight out of a lookup in lib/insights.js -- the model chose
// which lookup to run, but not what the numbers are. Showing them makes the answer checkable.
function EvidenceTable({ table }) {
  return (
    <div className="ask-evidence">
      <h4>{table.title}</h4>
      <table>
        <thead>
          <tr>
            {table.columns.map((c) => (
              <th key={c.key} style={c.type === 'text' ? { textAlign: 'left' } : undefined}>
                {c.label}
              </th>
            ))}
          </tr>
        </thead>
        <tbody>
          {table.rows.map((r, i) => (
            <tr key={i}>
              {table.columns.map((c) => {
                if (c.type === 'money') return <td key={c.key}>{fmt(r[c.key])}</td>;
                if (c.type === 'fav')
                  return (
                    <td key={c.key}>
                      <span className={r.favorable ? 'fav' : 'unfav'}>{r.favorable ? 'Fav' : '(Unfav)'}</span>
                    </td>
                  );
                return (
                  <td key={c.key} style={{ textAlign: 'left' }}>
                    {r[c.key]}
                  </td>
                );
              })}
            </tr>
          ))}
        </tbody>
      </table>
      {table.notes?.map((n, i) => (
        <p key={i} className="small-muted" style={{ margin: '4px 0 0' }}>
          {n}
        </p>
      ))}
    </div>
  );
}

export default function AskBox({ period }) {
  const [question, setQuestion] = useState('');
  const [loading, setLoading] = useState(false);
  const [result, setResult] = useState(null);
  const [error, setError] = useState(null);

  async function ask(q) {
    const text = (q ?? question).trim();
    if (!text || loading) return;
    setQuestion(text);
    setLoading(true);
    setError(null);
    setResult(null);
    try {
      const res = await fetch('/api/ask', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ question: text, period }),
      });
      const data = await res.json();
      if (!res.ok) setError(data.error || 'Something went wrong.');
      else setResult(data);
    } catch {
      setError('Could not reach the server. Please try again.');
    }
    setLoading(false);
  }

  return (
    <div>
      <div className="ask-row">
        <input
          type="text"
          value={question}
          onChange={(e) => setQuestion(e.target.value)}
          onKeyDown={(e) => {
            if (e.key === 'Enter') ask();
          }}
          placeholder="e.g. Why is Admin COGS Payroll and Benefits over budget?"
          disabled={loading}
          maxLength={500}
        />
        <button onClick={() => ask()} disabled={loading || !question.trim()}>
          {loading ? 'Thinking…' : 'Ask'}
        </button>
      </div>

      {!result && !error && !loading && (
        <p className="small-muted" style={{ marginTop: 8 }}>
          Try:{' '}
          {EXAMPLES.map((ex, i) => (
            <span key={ex}>
              {i > 0 && ' · '}
              <button className="ask-example" onClick={() => ask(ex)}>
                {ex}
              </button>
            </span>
          ))}
        </p>
      )}

      {error && <p className="ask-error">{error}</p>}

      {result && (
        <div className="ask-answer">
          <p style={{ whiteSpace: 'pre-wrap', margin: 0 }}>{result.answer}</p>
          {result.evidence?.length > 0 && (
            <>
              <p className="small-muted" style={{ margin: '12px 0 6px' }}>
                Figures used to produce this answer:
              </p>
              {result.evidence.map((t, i) => (
                <EvidenceTable key={i} table={t} />
              ))}
            </>
          )}
          <p className="small-muted" style={{ margin: '10px 0 0' }}>
            Generated by AI from the figures above. Check the numbers before quoting them externally.
          </p>
        </div>
      )}
    </div>
  );
}
